### ISSUE TITLE
Linking project to daset with data declaration without contract returns Server Error (500)

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#101]
**Describe the bug (current behaviour)**
When I try to link a dataset which has a data declaration without contract to a project I receive Server Error (500)

**To reproduce**
1. log in as admin
1.  Create fresh project
2. Create fresh dataset (through dataset tab - not through the project dataset section)
3. Add/create new data declaration for this dataset - select "Other (provenance unknown)"
eventually you can select " From existing data/samples (from an LCSB collaborator or your own past project) " and then edit declaration so the contract is empty
4. Try to add fresh dataset to fresh project.

**Expected behavior**
If a project can use some data (data declaration) without contract, then the operation of linkage should be possible. Otherwise, there should be an error message informing user that he has to provide contract first.

**Environment:**
 - Deployment: both daisy-test.lcsb.uni.lu deployment (10.240.6.196) and  production daisy.lcsb.uni.lu
 - Version  1.1.0
 - Browser  Firefox 68
 
 
**Additional information (error logs, screenshots)**
Error log:
```
DEBUG 2019-10-08 15:13:37,914 checker 10985 140638772946752 [AutoChecker] Checking permission "Permissions.EDIT" on Dataset: "new dataset of new project" for "admin": True.
DEBUG 2019-10-08 15:13:41,083 checker 10985 140638772946752 [AutoChecker] Checking permission "Permissions.EDIT" on Dataset: "new dataset of new project" for "admin": True.
ERROR 2019-10-08 15:13:41,096 log 10985 140638772946752 Internal Server Error: /dataset/7/edit
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/guardian/mixins.py", line 213, in dispatch
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 194, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 382, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 409, in _clean_form
    cleaned_data = self.clean()
  File "/home/daisy/daisy/core/forms/dataset.py", line 40, in clean
    if contract.project:
AttributeError: 'NoneType' object has no attribute 'project'
ERROR 2019-10-08 15:13:41,096 log 10985 140638772946752 Internal Server Error: /dataset/7/edit
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/guardian/mixins.py", line 213, in dispatch
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 194, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 382, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 409, in _clean_form
    cleaned_data = self.clean()
  File "/home/daisy/daisy/core/forms/dataset.py", line 40, in clean
    if contract.project:
AttributeError: 'NoneType' object has no attribute 'project'
```

**Comment by pinarpink** [comment]
fix verified on 8672baae574fb92455a0f97166ff91f383f84594
