### ISSUE TITLE
Error when building Solr schema

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#121]
**Describe the bug (current behaviour)**
Running
```
python36 manage.py build_solr_schema -f /var/solr/data/daisy/conf/schema.xml -r daisy
```
during deployment gives following error message:
```
Trying to write schema file located at /var/solr/data/daisy/conf/schema.xml
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/haystack/management/commands/build_solr_schema.py", line 67, in handle
    connections[using].get_backend().reload()
AttributeError: 'SolrSearchBackend' object has no attribute 'reload'
```

**To reproduce**

1. As root:
```
systemctl stop gunicorn
systemctl stop celery_worker
su -c 'psql -c "drop database daisy"' - postgres
su -c 'psql -c "create database daisy"' - postgres
su -c 'cd /home/daisy/daisy && git pull' - daisy
/usr/local/bin/pip install -e /home/daisy/daisy/ --upgrade
```
2. As daisy user:
```
cd /home/daisy/daisy/web/static/vendor/
git pull
npm ci
cd /home/daisy/daisy
python36 manage.py migrate && python36 manage.py build_solr_schema -f /var/solr/data/daisy/conf/schema.xml -r daisy
```

**Environment:**

 - Deployment: daisy-test.lcsb.uni.lu
 - Version 1.2.0

**Comment by vildead** [comment]
not reproducible anymore - closing
