### ISSUE TITLE
Server Error (500) thrown in ABOUT tab

### ISSUE THREAD

**Issue by evescat** [elixir-luxembourg/daisy#146]
**Describe the bug (current behaviour)**
The ABOUT tab https://10.240.6.75/about is not available, the http error 500 is thrown. The other  tabs (datasets, home, projects etc) are displayed correctly. 

**To reproduce**
Open  https://10.240.6.75/about

**Comment by vildead** [comment]
Some python packages were not updated. 
It should be fine now ;)

Can you please verify @evescat ? 

daisy log:
```
ERROR 2020-03-26 18:45:25,792 log 11231 140214010668864 Internal Server Error: /about
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/daisy/daisy/web/views/about.py", line 9, in about
    "app_version": pkg_resources.require("elixir-daisy")[0].version
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Django 2.2.10 (/usr/local/lib/python3.6/site-packages), Requirement.parse('Django==2.2.8'), {'elixir-daisy'})
```

**Comment by vildead** [comment]
Closing - issue resolved
