### ISSUE TITLE
403 Local custodian cannot access document in project

### ISSUE THREAD

**Issue by vildead** [elixir-luxembourg/daisy#276]
Error 403 received by local custodian when accessing document in a project 

Log:
```
EBUG 2021-09-03 15:26:33,926 checker 17454 139728188856128 [AutoChecker] Checking permission "Permissions.PROTECTED" on Document: "documents/project/2021/08/27/124_HeartMed_DMP_v3_20200911.pdf (HeartMed)" for "<name of the local custodian>": False.
WARNING 2021-09-03 15:26:33,927 log 17454 139728188856128 Forbidden (Permission denied): /documents/171/download
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/daisy/daisy/core/permissions/checker.py", line 194, in wrapper
    raise PermissionDenied
django.core.exceptions.PermissionDenied
```

**Comment by vildead** [comment]
related to #196
