### ISSUE TITLE
solr indexation of datadeclarations fails

### ISSUE THREAD

**Issue by neoflex** [elixir-luxembourg/daisy#56]
```
Failed to add documents to Solr: Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=core.datadeclaration.2] multiple values encountered for non multiValued field cohorts: [MUST (Diabetes MUltiplex family STudy), DeNoPa (De Novo Parkinson Longitudinal Study)]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/haystack/backends/solr_backend.py", line 76, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/usr/local/lib/python3.6/site-packages/pysolr.py", line 918, in add
    overwrite=overwrite, handler=handler)
  File "/usr/local/lib/python3.6/site-packages/pysolr.py", line 500, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/usr/local/lib/python3.6/site-packages/pysolr.py", line 412, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
pysolr.SolrError: Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=core.datadeclaration.2] multiple values encountered for non multiValued field cohorts: [MUST (Diabetes MUltiplex family STudy), DeNoPa (De Novo Parkinson Longitudinal Study)]]
```
the cohort field is now a many to many relationship but the solr schema https://github.com/elixir-luxembourg/daisy/blob/develop/core/search_indexes.py still specify the cohorts field as a charfield.

**Comment by vildead** [comment]
closing the issue. commit: decd5f6c0981ecb654ff3e92b6f4197c46b4fab9
