### ISSUE TITLE
Error 500 when updating dataset 

### ISSUE THREAD

**Issue by pinarpink** [elixir-luxembourg/daisy#93]
**Describe the bug (current behaviour)**

Dataset update form gives error 500 for certain records

**To reproduce**

1. login as admin
2. go to datasets page search for **luxpark**
3. edit the luxpark dataset
4. click submit (with or without making any changes in the editor)

**Expected behavior**
dataset should be saved fine once all required info is there.

**Environment:**

 - Deployment: [e.g. daisy.lcsb.uni.lu]
 - Version [e.g. 1.1.0]
 - Browser [e.g. Firefox 68.x]
 
**Additional information (error logs, screenshots)**

daisy.log contains the following trace:

`ERROR 2019-09-13 16:30:52,779 log 28835 139625891325760 Internal Server Error: /dataset/73/edit
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/guardian/mixins.py", line 213, in dispatch
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 194, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 382, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 409, in _clean_form
    cleaned_data = self.clean()
  File "/home/daisy/daisy/core/forms/dataset.py", line 40, in clean
    if contract.project:
AttributeError: 'NoneType' object has no attribute 'project' `

**Comment by pinarpink** [comment]
fix verified on 8672baae574fb92455a0f97166ff91f383f84594
